# Generated by Django 4.2.7 on 2026-01-06 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuggingFaceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='HuggingFace API access token', max_length=500, unique=True)),
                ('name', models.CharField(help_text='Friendly name for this token', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is available for assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Admin user who created this token', on_delete=django.db.models.deletion.CASCADE, related_name='created_hf_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'huggingface_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserHFTokenAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
                ('session_identifier', models.CharField(db_index=True, help_text='Identifier for the login session (e.g., refresh token jti)', max_length=255)),
                ('hf_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.huggingfacetoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hf_token_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_hf_token_assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_hf_tok_user_id_9e4424_idx'), models.Index(fields=['session_identifier'], name='user_hf_tok_session_045321_idx')],
            },
        ),
    ]
